# Autogenerated from /home/luke/Code/betaflight/tools/Enzyme/enzyme/test/lit.site.cfg.py.in
# Do not edit!

# Allow generated file to be relocatable.
import os
import platform
def path(p):
    if not p: return ''
    # Follows lit.util.abs_path_preserve_drive, which cannot be imported here.
    if platform.system() == 'Windows':
        return os.path.abspath(os.path.join(os.path.dirname(__file__), p))
    else:
        return os.path.realpath(os.path.join(os.path.dirname(__file__), p))


import os

#config.llvm_src_root = "/home/luke/Code/betaflight/tools/Enzyme/enzyme"
config.llvm_ver = "20"
config.llvm_obj_root = "/usr/lib/llvm/20"
config.llvm_tools_dir = "/usr/lib/llvm/20/bin"
if len("/home/luke/Code/betaflight/tools/enzyme_build") == 0:
  config.llvm_tools_dir = os.getcwd() + "/" + config.llvm_tools_dir
config.llvm_libs_dir = "/usr/lib/llvm/20/lib64"
config.enzyme_obj_root = "/home/luke/Code/betaflight/tools/enzyme_build"
config.target_triple = ""

config.llvm_shlib_ext = ".so"

config.targets_to_build = " AArch64 AMDGPU ARM AVR BPF Hexagon Lanai LoongArch MSP430 Mips NVPTX PowerPC RISCV SPIRV Sparc SystemZ VE WebAssembly X86 XCore"

has_mpfr_h = "1"
mpfr_lib_path = "/usr/lib64/libmpfr.so"
has_mpfr = "yes" if mpfr_lib_path != "MPFR_LIB_PATH-NOTFOUND" and has_mpfr_h == "1" else "no"

## Check the current platform with regex
import re
EAT_ERR_ON_X86 = ' '
if (re.match(r'^x86_64*', '') == None) :
  EAT_ERR_ON_X86 = '|| echo \"error is eaten\"'

for arch in config.targets_to_build.split():
    config.available_features.add(arch.lower() + '-registered-target')

# Support substitution of the tools and libs dirs with user parameters. This is
# used when we can't determine the tool dir at configuration time.
try:
    config.llvm_tools_dir = config.llvm_tools_dir % lit_config.params
    config.llvm_libs_dir = config.llvm_libs_dir % lit_config.params
except KeyError:
    e = sys.exc_info()[1]
    key, = e.args
    lit_config.fatal("unable to find %r parameter, use '--param=%s=VALUE'" % (key,key))

# excludes: A list of directories to exclude from the testsuite. The 'Inputs'
# subdirectories contain auxiliary inputs for various tests in their parent
# directories.
config.excludes = ['Inputs']

config.substitutions.append(('%shlibext', config.llvm_shlib_ext))
config.substitutions.append(('%lli', config.llvm_tools_dir + "/lli" + (" --jit-kind=mcjit" if int(config.llvm_ver) >= 13 else "")
))

opt = config.llvm_tools_dir + "/opt"
if len("/home/luke/Code/betaflight/tools/enzyme_build") == 0:
  opt = os.path.dirname(os.path.abspath(__file__)) + "/../enzyme-opt"

config.substitutions.append(('%opt', opt))

emopt = config.enzyme_obj_root + "/Enzyme/MLIR/enzymemlir-opt"
if len("/home/luke/Code/betaflight/tools/enzyme_build") == 0:
  emopt = os.path.dirname(os.path.abspath(__file__)) + "/../enzymemlir-opt"

eclang = config.llvm_tools_dir + "/clang"
if len("/home/luke/Code/betaflight/tools/enzyme_build") == 0:
  eclang = os.path.dirname(os.path.abspath(__file__)) + "/../enzyme-clang"
  resource = config.llvm_tools_dir + "/../clang/staging"
  eclang += " -resource-dir " + resource + " "
  eclang += "-I " + os.path.dirname(os.path.abspath(__file__)) + "/Integration" 

config.substitutions.append(('%eopt', emopt))
config.substitutions.append(('%llvmver', config.llvm_ver))
config.substitutions.append(('%FileCheck', config.llvm_tools_dir + "/FileCheck"))
config.substitutions.append(('%clang', eclang))
config.substitutions.append(('%O0TBAA', "-O1 -Xclang -disable-llvm-passes"))

oldPM = ((" --enable-new-pm=0" if int(config.llvm_ver) >= 13 else "")
                                 + ' -load=/home/luke/Code/betaflight/tools/enzyme_build/Enzyme/LLVMEnzyme-' + config.llvm_ver + config.llvm_shlib_ext 
                                 + (" --enzyme-attributor=0" if int(config.llvm_ver) >= 13 else ""))
newPM = ((" --enable-new-pm=1" if int(config.llvm_ver) in (12,13) else "")
                                 + ' -load-pass-plugin=/home/luke/Code/betaflight/tools/enzyme_build/Enzyme/LLVMEnzyme-' + config.llvm_ver + config.llvm_shlib_ext 
                                 + ' -load=/home/luke/Code/betaflight/tools/enzyme_build/Enzyme/LLVMEnzyme-' + config.llvm_ver + config.llvm_shlib_ext 
                                 + (" --enzyme-attributor=0" if int(config.llvm_ver) >= 13 else ""))
if len("/home/luke/Code/betaflight/tools/enzyme_build") == 0:
  oldPM = ((" --enable-new-pm=0" if int(config.llvm_ver) >= 13 else "")
                                 + (" --enzyme-attributor=0" if int(config.llvm_ver) >= 13 else ""))
  newPM = ((" --enable-new-pm=1" if int(config.llvm_ver) in (12,13) else "")
                                 + (" --enzyme-attributor=0" if int(config.llvm_ver) >= 13 else ""))

oldPMOP = oldPM
newPMOP = newPM
if int(config.llvm_ver) == 16:
  newPM += " -opaque-pointers=0"
  oldPM += " -opaque-pointers=0"

config.substitutions.append(('%loadEnzyme', oldPM if int(config.llvm_ver) < 16 else newPM))
config.substitutions.append(('%newLoadEnzyme', newPM))
config.substitutions.append(('%OPloadEnzyme', oldPMOP if int(config.llvm_ver) < 16 else newPMOP))
config.substitutions.append(('%OPnewLoadEnzyme', newPMOP))
config.substitutions.append(('%enzyme', ('-enzyme' if int(config.llvm_ver) < 16 else '-passes="enzyme"')))
config.substitutions.append(('%simplifycfg', ("simplify-cfg" if int(config.llvm_ver) < 11 else "simplifycfg")))
config.substitutions.append(('%loopmssa', ("loop" if int(config.llvm_ver) < 11 else "loop-mssa")))
config.substitutions.append(('%fc', ''))
config.substitutions.append(('%loadFortran', '-I/home/luke/Code/betaflight/tools/enzyme_build/modules'))

config.substitutions.append(('%loadBC', ''
                                 + ' /home/luke/Code/betaflight/tools/enzyme_build/BCLoad/BCPass-' + config.llvm_ver + config.llvm_shlib_ext
                                 ))
config.substitutions.append(('%BClibdir', '/home/luke/Code/betaflight/tools/Enzyme/enzyme/bclib/'))

oldPM = (((" -fno-experimental-new-pass-manager" if int(config.llvm_ver) < 14 else "-flegacy-pass-manager") if int(config.llvm_ver) >= 13 else "")
          + ' -Xclang -load -Xclang /home/luke/Code/betaflight/tools/enzyme_build/Enzyme/ClangEnzyme-' + config.llvm_ver + config.llvm_shlib_ext)
newPM = ((" -fexperimental-new-pass-manager" if int(config.llvm_ver) < 13 else "")
          + ' -fpass-plugin=/home/luke/Code/betaflight/tools/enzyme_build/Enzyme/ClangEnzyme-' + config.llvm_ver + config.llvm_shlib_ext
          + ' -Xclang -load -Xclang /home/luke/Code/betaflight/tools/enzyme_build/Enzyme/ClangEnzyme-' + config.llvm_ver + config.llvm_shlib_ext)

if len("/home/luke/Code/betaflight/tools/enzyme_build") == 0:
  oldPM = ((" -fno-experimental-new-pass-manager" if int(config.llvm_ver) < 14 else "-flegacy-pass-manager") if int(config.llvm_ver) >= 13 else "")
  newPM = (" -fexperimental-new-pass-manager" if int(config.llvm_ver) < 13 else "")

config.substitutions.append(('%loadClangEnzyme', oldPM if int(config.llvm_ver) < 15 else newPM))
config.substitutions.append(('%newLoadClangEnzyme', newPM))

config.substitutions.append(('%hasMPFR', has_mpfr))

# Let the main config do the real work.
cfgfile = "/home/luke/Code/betaflight/tools/Enzyme/enzyme/test/lit.cfg.py"
if len("/home/luke/Code/betaflight/tools/Enzyme/enzyme") == 0:
  cfgfile = os.path.dirname(os.path.abspath(__file__)) + "/lit.cfg.py"
lit_config.load_config(config, cfgfile)
