# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.0.0")
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.0.0...4.1)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS LLVMEnzyme-20 ClangEnzyme-20 ClangEnzymeFlags LLDEnzyme-20 LLDEnzymeFlags LLDEnzymeAssumeUnknownNoFree LLDEnzymeLooseTypeFlags LLDEnzymePrintTypeFlags LLDEnzymePrintFlags LLDEnzymeNoStrictAliasingFlags)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target LLVMEnzyme-20
add_library(LLVMEnzyme-20 MODULE IMPORTED)

# Create imported target ClangEnzyme-20
add_library(ClangEnzyme-20 MODULE IMPORTED)

set_target_properties(ClangEnzyme-20 PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "ENZYME_RUNPASS"
)

# Create imported target ClangEnzymeFlags
add_library(ClangEnzymeFlags INTERFACE IMPORTED)

set_target_properties(ClangEnzymeFlags PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-fplugin=\$<TARGET_FILE:ClangEnzyme-20>"
)

# Create imported target LLDEnzyme-20
add_library(LLDEnzyme-20 MODULE IMPORTED)

set_target_properties(LLDEnzyme-20 PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "ENZYME_RUNPASS"
)

# Create imported target LLDEnzymeFlags
add_library(LLDEnzymeFlags INTERFACE IMPORTED)

set_target_properties(LLDEnzymeFlags PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-flto"
  INTERFACE_LINK_OPTIONS "SHELL: -fuse-ld=lld;SHELL: -Wl,-mllvm -Wl,-load=\$<TARGET_FILE:LLDEnzyme-20>;SHELL: -Wl,--load-pass-plugin=\$<TARGET_FILE:LLDEnzyme-20>"
)

# Create imported target LLDEnzymeAssumeUnknownNoFree
add_library(LLDEnzymeAssumeUnknownNoFree INTERFACE IMPORTED)

set_target_properties(LLDEnzymeAssumeUnknownNoFree PROPERTIES
  INTERFACE_LINK_OPTIONS "SHELL: -Wl,-mllvm -Wl,-enzyme-assume-unknown-nofree=1"
)

# Create imported target LLDEnzymeLooseTypeFlags
add_library(LLDEnzymeLooseTypeFlags INTERFACE IMPORTED)

set_target_properties(LLDEnzymeLooseTypeFlags PROPERTIES
  INTERFACE_LINK_OPTIONS "SHELL: -Wl,-mllvm -Wl,-enzyme-loose-types=1"
)

# Create imported target LLDEnzymePrintTypeFlags
add_library(LLDEnzymePrintTypeFlags INTERFACE IMPORTED)

set_target_properties(LLDEnzymePrintTypeFlags PROPERTIES
  INTERFACE_LINK_OPTIONS "SHELL: -Wl,-mllvm -Wl,-enzyme-print-type=1"
)

# Create imported target LLDEnzymePrintFlags
add_library(LLDEnzymePrintFlags INTERFACE IMPORTED)

set_target_properties(LLDEnzymePrintFlags PROPERTIES
  INTERFACE_LINK_OPTIONS "SHELL: -Wl,-mllvm -Wl,-enzyme-print=1"
)

# Create imported target LLDEnzymeNoStrictAliasingFlags
add_library(LLDEnzymeNoStrictAliasingFlags INTERFACE IMPORTED)

set_target_properties(LLDEnzymeNoStrictAliasingFlags PROPERTIES
  INTERFACE_LINK_OPTIONS "SHELL: -Wl,-mllvm -Wl,-enzyme-strict-aliasing=0"
)

# Import target "LLVMEnzyme-20" for configuration "Release"
set_property(TARGET LLVMEnzyme-20 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(LLVMEnzyme-20 PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_RELEASE ""
  IMPORTED_LOCATION_RELEASE "/home/luke/Code/betaflight/tools/enzyme_build/Enzyme/LLVMEnzyme-20.so"
  IMPORTED_NO_SONAME_RELEASE "TRUE"
  )

# Import target "ClangEnzyme-20" for configuration "Release"
set_property(TARGET ClangEnzyme-20 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ClangEnzyme-20 PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_RELEASE ""
  IMPORTED_LOCATION_RELEASE "/home/luke/Code/betaflight/tools/enzyme_build/Enzyme/ClangEnzyme-20.so"
  IMPORTED_NO_SONAME_RELEASE "TRUE"
  )

# Import target "LLDEnzyme-20" for configuration "Release"
set_property(TARGET LLDEnzyme-20 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(LLDEnzyme-20 PROPERTIES
  IMPORTED_COMMON_LANGUAGE_RUNTIME_RELEASE ""
  IMPORTED_LOCATION_RELEASE "/home/luke/Code/betaflight/tools/enzyme_build/Enzyme/LLDEnzyme-20.so"
  IMPORTED_NO_SONAME_RELEASE "TRUE"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
